### ISSUE TITLE
Support Portainer

### ISSUE THREAD

**Issue by adoyle-h** [afbjorklund/nerdctld#8]
I want to manage nerdctl containers via [Portainer](https://github.com/portainer/portainer).

```
# compose.yaml
services:
  portainer:
    image: portainer/portainer-ce:2.19.4-alpine
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /home/adoyle/nerdctl.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000

volumes:
  portainer_data:
```

The Portainer needs docker.sock. So I start the nerdctld.

When I connect the nerdctl.sock in Portainer. It shows "Unable to create environment".

![CleanShot 2023-12-11 at 22 55 01@2x](https://github.com/afbjorklund/nerdctld/assets/1998490/d87c83ee-bc90-407d-8186-58193c919f4a)

The nerdctld logs:

```
[GIN] 2023/12/11 - 22:46:06 | 200 |        6.96µs |                 | HEAD     "/_ping"
[GIN] 2023/12/11 - 22:46:06 | 200 |       5.666µs |                 | HEAD     "/_ping"
[GIN] 2023/12/11 - 22:46:07 | 200 |  929.757317ms |                 | GET      "/v1.42/info"
[GIN] 2023/12/11 - 22:46:07 | 200 |   95.486035ms |                 | GET      "/v1.42/containers/json?all=1"
[GIN] 2023/12/11 - 22:46:07 | 200 |   51.972989ms |                 | GET      "/v1.42/containers/0d3952b16a8c/json"
```

The `DOCKER_HOST=unix://nerdctl.sock docker ps` works.

Could you please help me solve this problem?

## Environment

```
$ nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.7.5
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
  rootless
 Kernel Version: 6.5.2-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.4GiB
 Name: A02
 ID: 7ad6f773-a5c1-4e54-9d91-c881dfd0972a

$ nerdctld --version
nerdctld version 0.4.1
```
